### ISSUE TITLE
Incorrect Spelling in Navbar Section

### ISSUE THREAD

**Issue by NishantSinghhhhh** [NishantSinghhhhh/Open_Source#1]
Issue: 
![Screenshot 2024-09-14 003911](https://github.com/user-attachments/assets/68f68c63-8990-4f89-86d6-93b4fb6940ee)

The navbar section of the website contains several spelling mistakes that affect the overall user experience and professionalism of the site. These errors are present in key navigational links, which could confuse users and reduce the credibility of the platform. It is essential to ensure that all text, especially in prominent sections like the navbar, is properly checked and corrected. This issue should be addressed by reviewing the content, identifying all spelling mistakes, and correcting them to enhance clarity and maintain a high standard of quality across the website.

**Comment by Him-an-shi** [comment]
Sir I had solved this issue

**Comment by nysa1810** [comment]
sir i have corrected it

**Comment by ashsarin56** [comment]
Sir I have attempted to solve the issue.

**Comment by Ayushitripathi110505** [comment]
sir i have corrected it

**Comment by akashrwt337** [comment]
sir i have corrected it

**Comment by NishantSinghhhhh** [comment]
Navbar fixed
